name: Chachalog / Comment PR

on:
  workflow_call:

jobs:
  comment-pr:
    runs-on: ubuntu-slim
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ github.token }}

      - name: Is repo whitelisted?
        id: wl
        uses: jahia/jahia-modules-action/chachalog-is-whitelisted@v2
        with:
          repository: ${{ github.repository }}

      # If the repo does not contain a Chachalog config, this action
      # handles the creation of a default configuration, that should be
      # sufficient to get started
      - uses: jahia/jahia-modules-action/chachalog-default-config@v2
        if: ${{ steps.wl.outputs.whitelisted != 'true' }}

      - run: npx chachalog@^0.5 comment-pr
        if: ${{ steps.wl.outputs.whitelisted != 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
