name: Chachalog / Prepare Changelog

on:
  workflow_call:

jobs:
  prepare-changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 1
          token: ${{ github.token }}


      # If the repo does not contain a Chachalog config, this action
      # handles the creation of a default configuration, that should be 
      # sufficient to get started
      - uses: jahia/jahia-modules-action/chachalog-default-config@default-chachalog-config

      - run: npx chachalog@^0.4.4 prepare-next-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
