# Note: re-usable workflows must be in the .github/workflows folder, amongst other workflows dedicated
# to the jahia-modules-action repository. Thus using "reusable-" prefix to easily identify them.
name: Academy Documentation Publish

on:
  workflow_call:
    inputs:
      docs_path:
        type: string
        description: 'Path to the documentation folder'
        required: false
        default: 'docs/'
      graphql_endpoint:
        type: string
        description: 'GraphQL endpoint for the Academy'
        required: false
        default: 'https://academy.jahia.com/graphql'
    secrets:
      ACADEMY_AUTHORIZATION:
        description: 'Authorization token for the Academy'
        required: true

jobs:
  publish-academy-documentation:
    name: Publish Academy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish documentation on Academy
        uses: jahia/jahia-modules-action/academy-publish@v2
        with:
          docs_path: ${{ inputs.docs_path }}
          graphql_endpoint: ${{ inputs.graphql_endpoint }}
          graphql_authorization: ${{ secrets.ACADEMY_AUTHORIZATION }}
          publish: 'true'
